# sdl-jstest - Joystick Test Program for SDL
# Copyright (C) 2014 Ingo Ruhnke <grumbel@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

image: ubuntu:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get -qq update
  - apt-get -qq -y install
    clang-6.0
    g++-8
    cmake
    build-essential
    desktop-file-utils
    appstream-util
    libc++-dev
    libsdl1.2-dev
    libsdl2-dev
    software-properties-common

.build_sdl_jstest_template: &build_sdl_jstest
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARNINGS=ON -DWERROR=ON
    - make VERBOSE=1
    # - make test VERBOSE=1 ARGS="-V"

build:gcc:release:
  <<: *build_sdl_jstest
  variables:
    CXX: g++-8
    BUILD_TYPE: Release

build:clang:release:
  <<: *build_sdl_jstest
  variables:
    CXX: clang++-6.0
    BUILD_TYPE: Release

build:gcc:debug:
  <<: *build_sdl_jstest
  variables:
    CXX: g++-8
    BUILD_TYPE: Debug

build:clang:debug:
  <<: *build_sdl_jstest
  variables:
    CXX: clang++-6.0
    BUILD_TYPE: Debug

build:sdl_jstest:flatpak:
  stage: build
  script:
    - add-apt-repository -y ppa:alexlarsson/flatpak
    - apt-get -qq update
    - apt-get -qq -y install flatpak flatpak-builder
    - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak install -y flathub org.freedesktop.Platform org.freedesktop.Sdk
    - flatpak-builder --repo=build-flatpak-repo/ build-flatpak/ io.gitlab.sdl_jstest.sdl_jstest.json
    - flatpak build-bundle build-flatpak-repo/ sdl_jstest.flatpak io.gitlab.sdl_jstest.sdl_jstest
  artifacts:
    paths:
      - sdl_jstest.flatpak
      - build-flatpak-repo

build:sdl2_jstest:flatpak:
  stage: build
  script:
    - add-apt-repository -y ppa:alexlarsson/flatpak
    - apt-get -qq update
    - apt-get -qq -y install flatpak flatpak-builder
    - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak install -y flathub org.freedesktop.Platform org.freedesktop.Sdk
    - flatpak-builder --repo=build-flatpak-repo/ build-flatpak/ io.gitlab.sdl_jstest.sdl2_jstest.json
    - flatpak build-bundle build-flatpak-repo/ sdl2_jstest.flatpak io.gitlab.sdl_jstest.sdl2_jstest
  artifacts:
    paths:
      - sdl2_jstest.flatpak
      - build-flatpak-repo

# EOF #
